// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbeEDFM2JdZKtE3GV1UKGlfP0rhm6FSPY',
    appId: '1:297704881058:web:5ef32c9da3a60f508990fb',
    messagingSenderId: '297704881058',
    projectId: 'epflutter',
    authDomain: 'epflutter.firebaseapp.com',
    storageBucket: 'epflutter.appspot.com',
    measurementId: 'G-JH3V9DYHGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlKoELNTCpN_05L_K9Ejg-tFb20kRJ0Zw',
    appId: '1:297704881058:android:2a5df0887cace88c8990fb',
    messagingSenderId: '297704881058',
    projectId: 'epflutter',
    storageBucket: 'epflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcu8VBUv56tSdWdTOqdR4TSpS-_AQR9Fc',
    appId: '1:297704881058:ios:2095afecf3a1e4e38990fb',
    messagingSenderId: '297704881058',
    projectId: 'epflutter',
    storageBucket: 'epflutter.appspot.com',
    iosClientId: '297704881058-hn50h335bas5vdaav111ctv1rr6uo9f6.apps.googleusercontent.com',
    iosBundleId: 'com.example.newep',
  );
}
